apiVersion: v1
kind: ConfigMap
metadata:
  name: VibeStream-config
  namespace: vibestream-production
  labels:
    app.kubernetes.io/name: VibeStream
    app.kubernetes.io/part-of: VibeStream

data:
  REACT_APP_BACKEND_URL: "https://api.VibeStream.example.com"
  AI_ML_URL: "http://VibeStream-ai-ml:5000"
  REDIS_URL: "redis://VibeStream-redis:6379/1"
